{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{ if and .Values.pachd.rbac.create .Values.pachd.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ""
    suite: pachyderm
  name: {{ include "pachd.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ""
  kind: Role
  name: {{ include "pachd.fullname" . }}-worker
subjects:
- kind: ServiceAccount
  name: {{ .Values.pachd.worker.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{ end }}
